name: test img

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nndda/another-test-image:latest
      credentials:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - run: |
          ls -l /nnda.dev/
      - run: bun --version
      - run: python --version
      - run: |
          git clone https://github.com/nndda/nnda.dev.git ./repo --depth 1

          cp -rT repo /nnda.dev
          cd /nnda.dev

          ls -l ./

          python -m venv .
          source bin/activate
        shell: bash

      - run: ls -l ./
      - run: bun run build
