name: test img

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nndda/another-test-image:latest
      credentials:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - run: |
          bun --version
          python --version

          git clone https://github.com/nndda/nnda.dev.git ./repo --depth 1

          cp -rT repo /nnda.dev
          cd /nnda.dev

          python -m venv .
          source bin/activate

          bun run build
        shell: bash
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GH_PAT_EXT: ${{ secrets.GH_PAT_EXT }}
          SITE_EXT: ${{ secrets.SITE_EXT }}
          COMMIT_SHA: ${{ github.sha }}
