name: test img

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nndda/another-test-image:latest
      credentials:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - run: bun --version
      - run: python --version
      - run: ls -l /site/
